module.exports = {
    FEE_PER_BUY_USD: 0.05,
    MIN_DEPOSIT_USD: 5,
    MIN_PER_BUY_USD: 1.00,
    MIN_INTERVAL_MINUTES: 1,
    DEFAULT_SLIPPAGE_BPS: 300,
    GAS_BUFFER_SOL: 0.01,
    GAS_RESERVE_USD: 0.00,
    DEPOSIT_CHECK_INTERVAL_MS: 60000

};